version: "3.9"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: database

  web:
    build:
      context: ./
      dockerfile: DockerFile
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - os_data:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      -   postgres
    container_name: main


volumes:
  postgres_data:
  os_data: